### ISSUE TITLE
why its not working on my server

### ISSUE THREAD

**Issue by mindplayer** [NotSoSuper/NotSoBot#1]
i tried to type everything but nothing happens pls fix

**Comment by notcake** [comment]
Have you tried deleting and recreating your server?

**Comment by Lixquid** [comment]
Have you tried turning it off and on again?

**Comment by NotSoSuper** [comment]
i suggest you ban it

**Comment by qing5hu1** [comment]
FREEZE! THIS IS THE POLICE, DROP YOUR MEMES AND PUT YOUR HANDS UP WHERE I CAN SEE THEM

**Comment by roboderpy** [comment]
NotSoBot doesn't like you

**Comment by GameOveer** [comment]
lol the issue

**Comment by meepdarknessmeep** [comment]
haha losers you thought this issue was dead?

**Comment by NotSoSuper** [comment]
they THOUGHT 
![image](https://user-images.githubusercontent.com/4484641/31852639-1088ade4-b649-11e7-9ad9-4b6dcfef11b8.png)

**Comment by Cylifio** [comment]
fix

**Comment by emptixo** [comment]
Fix

**Comment by ConnorMcF** [comment]
fix?

**Comment by emptix0** [comment]
Have u tried to kys ?

**Comment by menislash** [comment]
delete system 31

**Comment by repeatingwish** [comment]
delete system 69

**Comment by meepen** [comment]
Still not work

**Comment by Cylifio** [comment]
fix!!!!!!!!!!!!!!!

**Comment by empt1xo** [comment]
Wtf!!!! Please fix
