### ISSUE TITLE
async def on_ready(self): error

### ISSUE THREAD

**Issue by steampunko** [NotSoSuper/NotSoBot#12]
File "./bot.py", line 145
    async def on_ready(self):
            ^
SyntaxError: invalid syntax

I can't seem to get this error to go away... Help!

**Comment by NotSoSuper** [comment]
You need to use a python version with the `async` keyword support (3.5+).

I also highly suggest you don't waste your time trying to self-host the bot, you're clearly new to Python and this isn't a beginners project.

**Comment by steampunko** [comment]
I have actually used python before, and I am using 3.6.1
