### ISSUE TITLE
Remind displays incorrect time

### ISSUE THREAD

**Issue by washingdone** [NotSoSuper/NotSoBot#14]
When using .remind the confirmation message is a minute behind, although it reminds you at the correct time. Example: ".remind your reminder 70m" displays "Reminder set for `1 hour 9 minutes` from now" but gives "Reminder: `your reminder`" in 70 minutes.

**Comment by NotSoSuper** [comment]
It's not a minute behind, it's just the millisecond delay between the processing of code and the message.
I'll place the time it says higher in the code flow so it doesn't show as behind.
