### ISSUE TITLE
SQLAlchemy import error

### ISSUE THREAD

**Issue by TheEvilSkeletor** [NotSoSuper/NotSoBot#19]
I've downloaded all the requirements for NotSoBot, yet when I attempt to launch bot.py/bot0.py, I get an error code that says the following:
`line 7 in <module> ImportError: No module named 'sqlalchemy'` 

And yes, I _do_ have sqlalchemy. (Flask-sqlalchemy as well.)

**Comment by ozzt** [comment]
>trying to selfhost notsobot

**Comment by emptix0** [comment]
^

**Comment by emptix0** [comment]
Lol 1002 your discord account got banned 😂😂😂
