### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by matmen** [NotSoSuper/NotSoBot#22]
# Suggestion
Hey there! This is just a quick little suggestion i sketched out earlier. The basic idea is that you fix your shit.
### `But how would I do that?` you may ask
* idk, its ur bot.
* fix it.

**Comment by Cylifio** [comment]
fix your bot
😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡

**Comment by adk8674** [comment]
Fix, when?

**Comment by emptixo** [comment]
NSS FIX YOUR SHIT ALREADY

**Comment by matmen** [comment]
hello yes bot is broken please fix @NotSoSuper??

**Comment by emptix0** [comment]
Yes ^ i agree with mat plz fix it !

**Comment by GummiWummiBear** [comment]
it's fixed

**Comment by NotSoSuper** [comment]
workers rewrite eta this summer

**Comment by dm4uz3** [comment]
still not fixed

**Comment by matmen** [comment]
> still not fixed

^

**Comment by nm17** [comment]
> > still not fixed
> 
> ^

^

**Comment by matmen** [comment]
> > > still not fixed
> > 
> > 
> > ^
> 
> ^

^

**Comment by dr03m** [comment]
> > > > still not fixed
> > > 
> > > 
> > > ^
> > 
> > 
> > ^
> 
> ^

^ seems like the bot is slowly dying. Sad.

**Comment by nm17** [comment]
> > > > > still not fixed
> > > > 
> > > > 
> > > > ^
> > > 
> > > 
> > > ^
> > 
> > 
> > ^
> 
> ^ seems like the bot is slowly dying. Sad.

It's dead now. Big sad

**Comment by dr03m** [comment]
bots down now

**Comment by rafaelwastaken** [comment]
🦀 workers rewrite is dead 🦀

**Comment by matmen** [comment]
fix?
