### ISSUE TITLE
Literally broken 

### ISSUE THREAD

**Issue by emptixo** [NotSoSuper/NotSoBot#32]
THE BOT JUST PINGED WITH A FUCKING 90 MS FFS FIX YOUR SHITTY INTERNET , FUCKING FIX YOUR RYTARDED SLOW ASS BOT ALREADY

**Comment by ConnorMcF** [comment]
have you tried unplugging it, then plugging it back in again?

**Comment by emptixo** [comment]
YES NOT WORKING FIX IT CUNTS

**Comment by ConnorMcF** [comment]
ok, but have you tried restarting excel?

**Comment by emptixo** [comment]
Thanks for muteing that annoying kid, now can I whisper wholesome things in your asshole 👅👅💯💯🙊🙊👀👀💦💦🔥🔥🍑🍑👄👄👌👌👀 ?
