### ISSUE TITLE
fix ur docs pls

### ISSUE THREAD

**Issue by RCXcrafter** [NotSoSuper/NotSoBot#39]
Not updating your source is one thing but at least have an updated documentation.
Also, the tag module needs better documentation, just adding "this is custom commands" would be a big improvement. Other useful help commands should also be listed there, such as .t imagescript and however many more there might be.

**Comment by emptix0** [comment]
Also unblacklist me kthanks.

**Comment by RCXcrafter** [comment]
Get outta here, make your own issue or something.

**Comment by emptix0** [comment]
Lol no.

**Comment by TheRealLegitCuck** [comment]
Kys

**Comment by Fogapod** [comment]
Use `.tag {tag}`, dogsong made documentation for most of the tags
