### ISSUE TITLE
rip notsobot

### ISSUE THREAD

**Issue by repeatingwish** [NotSoSuper/NotSoBot#40]
it died because of a joke

**Comment by internetpersoncode** [comment]
rip

**Comment by Scaprod** [comment]
What was the joke?

**Comment by repeatingwish** [comment]
https://cdn.discordapp.com/attachments/422463401122463745/438478190789263360/FhOOj9.png

**Comment by Scaprod** [comment]
We want NotSoBot back!!

**Comment by repeatingwish** [comment]
ikr

**Comment by Scaprod** [comment]
When was the joke?

**Comment by repeatingwish** [comment]
idk. i just open discord and go to neo and its gone. just like that

**Comment by Scaprod** [comment]
Neo?

**Comment by ghost** [comment]
damm sjws

**Comment by repeatingwish** [comment]
The NEO Lounge

**Comment by ghost** [comment]
@Scaprod discord.io/theneo , it's a server lul

**Comment by repeatingwish** [comment]
good server too

**Comment by Scaprod** [comment]
Is the owner Neo?

**Comment by ghost** [comment]
@Scaprod No lol, I own the server with someone else :p
