### ISSUE TITLE
Update the source code to its latest version

### ISSUE THREAD

**Issue by sks316** [NotSoSuper/NotSoBot#44]
From what I've heard, the source code here is nearly a year old and needs to be updated. Please do so as soon as you can.

**Comment by icecream42** [comment]
this tbh

**Comment by ghost** [comment]
this tbh

**Comment by ghost** [comment]
at least give us a reason why you wont release, its obvious nsb isnt gonna return for a while

**Comment by emptix0** [comment]
^

**Comment by icecream42** [comment]
this tbh

**Comment by ghost** [comment]
@Rhodesia NSB is now online with a new account, check NotSoServer. Most likely NSB will stay closed-source because a majority of the code is proprietary or uses methods or features NSS wants private.
