### ISSUE TITLE
dont update source

### ISSUE THREAD

**Issue by ghost** [NotSoSuper/NotSoBot#52]
I dont want 200 notsobots.

Also I bet you are reading this.

**Comment by rafaelwastaken** [comment]
update source from beyond the grave

**Comment by plethorum** [comment]
you couldve had 200 notsobots regardless... the code is right here on github anyway, so an updated source cant do anything but good

**Comment by ghost** [comment]
@plethorum Updating the source will only promote more "I made this" scenarios. For someone who wont just copy NSS's code it would be easy to port the source to a more up-to-date library version
