### ISSUE TITLE
rip notsosuper

### ISSUE THREAD

**Issue by rafaelwastaken** [NotSoSuper/NotSoBot#53]
rip

**Comment by Cylifio** [comment]
![sapou](https://user-images.githubusercontent.com/32244810/39282618-16daff4a-48d8-11e8-98c5-6fa9e59022dc.gif)

**Comment by ghost** [comment]
This is so sad.
Can we get 10 likes?

**Comment by icecream42** [comment]
((()))

**Comment by iamnotdanonplsfuckme** [comment]
lol no

**Comment by Scaprod** [comment]
He never died.

**Comment by Dominic18** [comment]
Ok boomer...
