### ISSUE TITLE
fix it

### ISSUE THREAD

**Issue by elsorino** [NotSoSuper/NotSoBot#56]
bot won't respond to me and deleting my server didn't work

**Comment by yellowcooln** [comment]
Give it some time. The bot just went back up. So I bet it's being used a lot. I know in the servers that in it is.

**Comment by emptix0** [comment]
Close this issue

**Comment by emptix0** [comment]
CLOSE THIS ISSUE

**Comment by cl0ck-byte** [comment]
ANWSER: [click here](https://cdn.discordapp.com/attachments/265199259291222016/439464237304250368/30429848_590024591354804_1152291727_n.png)

**Comment by emptix0** [comment]
No .

**Comment by emptix0** [comment]
Delete this issue !
