### ISSUE TITLE
WHY NOTSOBOT IS DEAD? (anwser)

### ISSUE THREAD

**Issue by cl0ck-byte** [NotSoSuper/NotSoBot#57]
# **Because this: [click here](https://cdn.discordapp.com/attachments/265199259291222016/439464237304250368/30429848_590024591354804_1152291727_n.png)**

**Comment by emptix0** [comment]
Delete this issue lol

**Comment by emptix0** [comment]
![](https://i.imgur.com/p5kJRJX.png)
