### ISSUE TITLE
don't run ur fucking bot on root

### ISSUE THREAD

**Issue by meepdarknessmeep** [NotSoSuper/NotSoBot#7]
also don't ssh into root u fuckhead

**Comment by NotSoSuper** [comment]
no u

**Comment by mcd1992** [comment]
agreed very offended .kys

**Comment by OutdatedVersion** [comment]
o

**Comment by meepdarknessmeep** [comment]
@NotSoSuper

**Comment by MiakoMoto** [comment]
running any sort of public bot as root is the single worst fucking thing you could do. you should be burned at the stake for running this as root. reported to the cyberpolice

**Comment by SpencerSharkey** [comment]
rm -rf /

**Comment by GlitchMasta47** [comment]
Sorry, is this even a fucking issue? It's more like advice. But we have [a really cool website](https://www.google.com/) for that.

**Comment by meepdarknessmeep** [comment]
Who the fuck are you kid

**Comment by meepdarknessmeep** [comment]
Why the fuck are you linking Google ducking retard you aren't funny nor cool

**Comment by SpencerSharkey** [comment]
Even if it wasn't an issue bringing it up is even worse than leaving it be

![c37vckcvmaaqdvc](https://cloud.githubusercontent.com/assets/4871369/26526828/8c4b9ae4-4354-11e7-9091-0af38e3f0e4b.png)

**Comment by xshotD** [comment]
@GlitchMasta47 pls

**Comment by meepdarknessmeep** [comment]
everyone can already find it as root because any error involving a file location has /root/ in its path

**Comment by NotSoSuper** [comment]
done
![image](https://cloud.githubusercontent.com/assets/4484641/26534209/c712a9a6-43ef-11e7-9e3e-4fd92a22ec9f.png)

**Comment by SpencerSharkey** [comment]
putty is for scrubsSent from Nylas Mail, the best free email app for work
          
            
            On May 28 2017, at 9:51 pm, NotSoSuper <notifications@github.com> wrote:
            
            
              done

**Comment by mcd1992** [comment]
DDoSing ns542573
