### ISSUE TITLE
.meme shouldn't require a URL

### ISSUE THREAD

**Issue by Kampfkarren** [NotSoSuper/NotSoBot#74]
Why can't it just use the last embed like everything else?

**Comment by empt1xo** [comment]
@notsosuper fix ?

**Comment by NotSoSuper** [comment]
The only solution would be to add something like `^` as an argument to use the last embed. Having the url as the first argument for a command, that requires text arguments, comes with its drawbacks: such as not being able to differentiate text and a valid image argument.

No ETA on adding that new argument.
