### ISSUE TITLE
Faceapp Internal Server Error

### ISSUE THREAD

**Issue by EvanTypefaces** [NotSoSuper/NotSoBot#75]
FaceApp commands don't work 3/4 of the time because of this bullshit:
<h1>Internal Server Error</h1>
    <p>
        The server encountered an internal error and cannot complete
        your request.
    </p>

**Comment by empt1xo** [comment]
fix!!!!!11

**Comment by nm17** [comment]
@NotSoSuper pls answer

**Comment by NotSoSuper** [comment]
Please read the last comment on ##72
