### ISSUE TITLE
bruh i have been kicked doing the notsochallenge, but i mentioned 10 ppl

### ISSUE THREAD

**Issue by Xephobia** [NotSoSuper/NotSoBot#88]
send me the serv invite

**Comment by Dominic18** [comment]
Same

**Comment by rafaelwastaken** [comment]
Unfortunately, as you have failed the NotSoChallenge, you will remain banned indefinitely.

**Comment by Xephobia** [comment]
@fofofofofofofofoXD i have mentioned 10 ppl, this is glitchy, can a mod deban me?

**Comment by Dominic18** [comment]
You guys are jerks so stfu

**Comment by Dominic18** [comment]
> Unfortunately, as you have failed the NotSoChallenge, you will remain banned indefinitely.
Thats dumb... @fofofofofofofofoXD
